-keep class com.thesourceofcode.jadec.MainApplication
-keep class com.thesourceofcode.jadec.MainApplication { *; }
-keep class com.thesourceofcode.jadec.utils.logging.** { *; }
-keep class com.thesourceofcode.jadec.test.** { *; }
-keep class androidx.test.** { *; }
-keep class androidx.multidex.** { *; }
-keep class kotlin.** { *; }
